FROM microsoft/nanoserver
MAINTAINER Ian Bebbington <docker@bebbs.co.uk>
LABEL Description="Neo4j running on Microsoft Nanoserver" Version="0.1"
ADD Root /
ADD Start-CoreNLP.ps1 /
RUN setx /M JAVA_HOME C:\Apps\Jre
EXPOSE 9000
ENTRYPOINT [ "powershell.exe", "C:/Start-CoreNLP.ps1" ]
