FROM microsoft/nanoserver
MAINTAINER Ian Bebbington <docker@bebbs.co.uk>
LABEL Description="ElasticSearch running on Microsoft Nanoserver" Version="0.1"
ADD Root /
ADD Start-ElasticSearch.ps1 /
RUN setx /M JAVA_HOME C:\Apps\Jre
EXPOSE 9200
ENTRYPOINT [ "powershell.exe", "C:/Start-ElasticSearch.ps1" ]
